"""
bridge.py — orchestrates the full Falcon-512 ZK proof pipeline:

  1. Build a Stellar XDR transaction (Python)
  2. Generate Falcon-512 keypair + sign via Rust keygen binary → proof_inputs.json
  3. Run the RISC Zero host prover → proof.json
  4. Print the stellar CLI command to verify on-chain via Soroban

Usage:
    python bridge.py [--local] [--skip-sign]

Proving modes (checked in order):
  Boundless network (Groth16, no local GPU needed):
    BOUNDLESS_RPC_URL        — Base Sepolia RPC, e.g. https://sepolia.base.org
    BOUNDLESS_PRIVATE_KEY    — hex private key of your Base Sepolia wallet (needs testnet ETH)
    BOUNDLESS_ORDER_STREAM_URL — defaults to https://base-sepolia.boundless.network
    PINATA_JWT               — Pinata API JWT for storing guest ELF (free tier ok)

  Local dev mode (STARK only, no Groth16, no on-chain verify):
    omit BOUNDLESS_RPC_URL   — falls back to local CPU proving (~7 min)

Soroban:
    VERIFIER_CONTRACT_ID — Nethermind Groth16 verifier contract on Stellar testnet
    SPHINCS_CONTRACT_ID  — your deployed Soroban wrapper contract
"""

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

# Parse --local flag before loading .env
_local_mode = "--local" in sys.argv

# Auto-load .env if present (skip Boundless vars in local mode)
_env_file = Path(__file__).parent / ".env"
if _env_file.exists():
    _skip = {"BOUNDLESS_RPC_URL", "BOUNDLESS_PRIVATE_KEY", "BOUNDLESS_ORDER_STREAM_URL"} if _local_mode else set()
    for line in _env_file.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            if k.strip() not in _skip:
                os.environ.setdefault(k.strip(), v.strip())

# Project root
ROOT = Path(__file__).parent
PROVER_DIR = ROOT / "prover"
PROOF_INPUTS = ROOT / "proof_inputs.json"
PROOF_OUTPUT = ROOT / "proof.json"


def run_step(label: str, fn):
    print(f"\n{'='*60}")
    print(f"  {label}")
    print(f"{'='*60}")
    return fn()


def step_keygen_and_sign():
    sys.path.insert(0, str(ROOT))
    from sphincs import build_stellar_tx_bytes, generate_and_sign

    tx_bytes = build_stellar_tx_bytes()
    print(f"Stellar XDR ({len(tx_bytes)} bytes): {tx_bytes[:32]}...")

    data = generate_and_sign(tx_bytes, output_path=str(PROOF_INPUTS))
    return data


def step_prove():
    env = os.environ.copy()
    use_boundless = bool(os.environ.get("BOUNDLESS_RPC_URL"))

    cmd = [
        "cargo", "+risc0", "run",
        "--release",
        "--manifest-path", str(PROVER_DIR / "Cargo.toml"),
        "-p", "sphincs-host",
        "--bin", "sphincs-host",
    ]
    if use_boundless:
        cmd += ["--features", "boundless"]
        print("Boundless mode: proof will be generated by the network (Groth16)")
    else:
        print("Local mode: proof will be generated on this machine (STARK, ~7 min)")

    cmd += ["--", str(PROOF_INPUTS), str(PROOF_OUTPUT)]
    # Enable RISC Zero verbose logging
    env["RISC0_INFO"] = "1"
    env["RUST_LOG"] = "info"
    env["RAYON_NUM_THREADS"] = "8"
    print(f"Running: {' '.join(cmd)}")
    import time
    t_start = time.time()
    result = subprocess.run(cmd, env=env)
    print(f"\nProver wall time: {time.time() - t_start:.1f}s")
    if result.returncode != 0:
        print("\nProver failed. Check Cargo output above.")
        sys.exit(1)


def step_print_soroban_cmd():
    proof = json.loads(PROOF_OUTPUT.read_text())

    verifier_id = os.environ.get("VERIFIER_CONTRACT_ID", "CBY3GOBGQXDGRR4K2KYJO2UOXDW5NRW6UKIQHUBNBNU2V3BXQBXGTVX7")
    falcon_id   = os.environ.get("SPHINCS_CONTRACT_ID", "<deploy first — see below>")
    wasm_path   = ROOT / "soroban" / "target" / "wasm32v1-none" / "release" / "sphincs_verifier.wasm"

    print(f"\nProof ready:")
    print(f"  image_id:    {proof['image_id']}")
    print(f"  journal:     {proof['journal']}")
    print(f"  pubkey_hash: {proof['pubkey_hash']}")
    print(f"  tx_hash:     {proof['tx_hash']}")
    print(f"  seal_len:    {len(bytes.fromhex(proof['seal']))} bytes")

    not_deployed = falcon_id.startswith("<")

    if not_deployed:
        print(f"""
── Step A: Deploy the Falcon verifier wrapper contract ──────────────────────
stellar contract deploy \\
  --wasm {wasm_path} \\
  --source-account YOUR_SECRET_KEY \\
  --network testnet

# Save the returned contract ID, then:

── Step B: Configure the Nethermind verifier address ────────────────────────
stellar contract invoke \\
  --id <YOUR_FALCON_VERIFIER_CONTRACT_ID> \\
  --source-account YOUR_SECRET_KEY \\
  --network testnet \\
  -- set_verifier \\
  --verifier {verifier_id}

# Set SPHINCS_CONTRACT_ID=<YOUR_FALCON_VERIFIER_CONTRACT_ID> in .env, then re-run bridge.py.
""")
    else:
        print(f"""
── Verify proof on Stellar testnet ──────────────────────────────────────────
stellar contract invoke \\
  --id {falcon_id} \\
  --source-account YOUR_SECRET_KEY \\
  --network testnet \\
  -- verify_falcon_tx \\
  --seal {proof['seal']} \\
  --image_id {proof['image_id']} \\
  --journal {proof['journal']} \\
  --pubkey_hash {proof['pubkey_hash']} \\
  --tx_hash {proof['tx_hash']}

Nethermind verifier: {verifier_id}
Note: --seal must be a real Groth16 seal (from Boundless), not a local STARK seal.
""")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--skip-sign", action="store_true",
                        help="Skip key gen/signing, reuse existing proof_inputs.json")
    parser.add_argument("--local", action="store_true",
                        help="Force local STARK mode (ignore Boundless env vars)")
    args = parser.parse_args()

    if not args.skip_sign:
        run_step("Step 1: Falcon-512 keygen + Stellar XDR sign", step_keygen_and_sign)
    else:
        print("Skipping sign step, using existing proof_inputs.json")

    run_step("Step 2: RISC Zero proving", step_prove)
    run_step("Step 3: Soroban invocation", step_print_soroban_cmd)

    print("\nDone.")


if __name__ == "__main__":
    main()
